[General]
AppName = "ginadmin"
RunMode = "debug" # debug/test/release
PprofAddr = "localhost:6060"
DisableSwagger = false
DisablePrintConfig = false
DisableInitMenu = false

[General.HTTP]
Addr = ":8080"
ReadTimeout = 60
WriteTimeout = 60
IdleTimeout = 10
ShutdownTimeout = 10
CertFile = ""
KeyFile = ""

[Storage]

[Storage.Cache]
Type = "badger" # memory/badger/redis
Delimiter = ":"

[Storage.Cache.Memory]
CleanupInterval = 60

[Storage.Cache.Badger]
Path = "data/cache"

[Storage.Cache.Redis]
Addr = ""
Username = ""
Password = ""
DB = 0

[Storage.DB]
Debug = true
Type = "sqlite3"
DSN = "data/sqlite/ginadmin.db"
MaxLifetime = 86400
MaxIdleTime = 3600
MaxOpenConns = 100
MaxIdleConns = 50
TablePrefix = ""

[Middleware]

[Middleware.CORS]
Enable = false
AllowOrigins = ["*"]
AllowMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
AllowHeaders = ["*"]
MaxAge = 86400
AllowWildcard = true
AllowWebSockets = true
AllowFiles = true

[Middleware.Recovery]
Skip = 3

[Middleware.Trace]
RequestHeaderKey = "X-Request-Id"
ResponseTraceKey = "X-Trace-Id"

[Middleware.Logger]
MaxOutputRequestBodyLen = 4096 # bytes
MaxOutputResponseBodyLen = 1024 # bytes

[Middleware.CopyBody]
MaxContentLen = 33554432 # 32M

[Middleware.Auth]
Disable = true
SkippedPathPrefixes = ["/api/rbac/v1/login"]
SigningMethod = "HS512"
SigningKey = "XnEsT0S@"
Expired = 86400 # seconds

[Middleware.Auth.Store]
Type = "badger" # memory/badger/redis
Delimiter = ":"

[Middleware.Auth.Store.Memory]
CleanupInterval = 60

[Middleware.Auth.Store.Badger]
Path = "data/auth"

[Middleware.Auth.Store.Redis]
Addr = ""
Username = ""
Password = ""
DB = 0

[Middleware.RateLimiter]
Enable = true
Period = 30 # seconds
MaxRequestsPerIP = 120
MaxRequestsPerUser = 120

[Middleware.RateLimiter.Store]
Type = "memory" # memory/redis

[Middleware.RateLimiter.Store.Memory]
Expiration = 3600
CleanupInterval = 60

[Middleware.RateLimiter.Store.Redis]
Addr = ""
Username = ""
Password = ""
DB = 0

[Middleware.Casbin]
Disable = false
SkippedPathPrefixes = ["/api/rbac/v1/login", "/api/rbac/v1/current"]
Debug = true
AutoLoadInterval = 60 # seconds

[Middleware.Static]
SkippedPathPrefixes = ["/api"]

[Util]

[Util.Captcha]
Length = 4
Width = 400
Height = 160
CacheType = "memory"

[Util.Captcha.Redis]
Addr = ""
Username = ""
Password = ""
DB = 0
KeyPrefix = "captcha:"

[Dictionary]
UserCacheExpire = 4 # Hours

[Dictionary.RootUser]
ID = "root"
Username = "root"
Password = "abc-123"
Name = "Root"
