[Logger]
Debug = true
Level = "debug"
CallerSkip = 1

[Logger.File]
Enable = false
Path = "data/ginadmin.log"
MaxBackups = 20 # Files
MaxSize = 64 # MB

[[Logger.Hooks]]
Enable = false
Level = "info"
Type = "gorm" # gorm

[Logger.Hooks.Options]
Debug = true
Type = "sqlite3" # mysql/postgres/sqlite3
DSN = "data/logger.db"
MaxOpenConns = 16
MaxIdleConns = 8
MaxLifetime = 86400
MaxIdleTime = 7200
TablePrefix = ""
